### ISSUE TITLE
Do you have a project.clj for this or a quick tl;dr on how to make it work? 

### ISSUE THREAD

**Issue by deltabravozulu** [GutZuFusss/DurakBot#1]

**Comment by GutZuFusss** [comment]
not certain, but shouldn't the deps.edn be enough? 
there is a -main function in bot.clj, most IDEs should be able to make it work from there (i use cursive).

btw: its only API reversing so far. no actual game logic is implemented.

**Comment by deltabravozulu** [comment]
Ah, got it. Yep--worked. Thanks!

**Comment by GutZuFusss** [comment]
A public fork would be much appreciated, very interested in what you might do with this. If you need more insights on how this works don't hesistate to HMU
